### ISSUE TITLE
Overflow shouldn't wrap

### ISSUE THREAD

**Issue by Half-Shot** [sbts/UserStyles-vector-im#4]
The room name here is quite long, but it shouldn't go onto the next line.
https://ptpb.pw/APXKDBtAb1uc3_0kfXuX6zRaovtK.png

**Comment by sbts** [comment]
```
Interesting, I can't duplicate this.

It looks like you had both crunch and slate enabled.
However, crunch should prevent wrapping, instead fixing the room
list width to be the same as the longest name.

What browser and OS are you using, and can you please tell me the
full room name that wrapped.
(even better if you can get the raw json containing the room name)

On 09/05/16 02:16, Will Hunt wrote:


  https://ptpb.pw/APXKDBtAb1uc3_0kfXuX6zRaovtK.png
  —
    You are receiving this because you are subscribed to this
    thread.
    Reply to this email directly or view
      it on GitHub
```

**Comment by Half-Shot** [comment]
Full title is "Future_Suture (PM on irc.freenode.net)"
Firefox 46 on Linux
(FYI, I turned off slate and it still happens)

**Comment by sbts** [comment]
Hmm, I'll play around with this when I can, to be honest I'm not even sure where to start unless I can get it to happen here!

**Comment by sbts** [comment]
I've finally managed to reproduce this.
Not sure when I'll get a fix sorted right now but at least I can see the issue :-)
